# Copyright 2023 EPFL
# Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#
# Author: Simone Machetti - simone.machetti@epfl.ch

target extended-remote localhost:3333
set confirm off
monitor reset init
load /home/xilinx/x-heep-femu-sdk/sw/riscv/build/code.elf
file /home/xilinx/x-heep-femu-sdk/sw/riscv/build/code.elf
b _end
c
quit
