#ifndef _DEFINITIONS_H
#define _DEFINITIONS_H

#define VADC_ACQUISITION_SAMPLES 	5998
#define X_HEEP_SAMPLING_BUFFER_SAMPLES 	32
#define WORD_SIZE_BYTES 	1
#define WORD_SIZE_BITS 	8
#define ADC_CH_DATA_MASK 	127
#define VADC_SAMPLING_FREQ_HZ 	700000.0
#define ENABLE_PRINTF 	1
#endif