#ifndef _DEFINITIONS_H
#define _DEFINITIONS_H

#define VADC_ACQUISITION_SAMPLES 	2549
#define X_HEEP_SAMPLING_BUFFER_SAMPLES 	50
#define WORD_SIZE_BYTES 	4
#define VADC_SAMPLING_FREQ_HZ 	700000
#define ENABLE_PRINTF 	1
#define OUTPUT_START_SEQ 	"# "
#define OUTPUT_DIVIDER 	"|"
#define OUTPUT_END_SEQ 	"#---"
#endif