#ifndef _DEFINITIONS_H
#define _DEFINITIONS_H

#define VADC_ACQUISITION_SAMPLES 	5998
#define X_HEEP_SAMPLING_BUFFER_SAMPLES 	32
#define WORD_SIZE_BYTES 	2
#define WORD_SIZE_BITS 	16
#define ADC_CH_DATA_MASK 	16383
#define VADC_SAMPLING_FREQ_HZ 	700000
#define ENABLE_PRINTF 	1
#define OUTPUT_START_SEQ 	"# "
#define OUTPUT_DIVIDER 	"|"
#define OUTPUT_END_SEQ 	"#---"
#endif