// Copyright 2022 OpenHW Group
// Solderpad Hardware License, Version 2.1, see LICENSE.md for details.
// SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1

#ifndef COREV_MINI_MCU_H_
#define COREV_MINI_MCU_H_

#ifdef __cplusplus
extern "C" {
#endif  // __cplusplus

#define MEMORY_BANKS 2

#define DEBUG_START_ADDRESS 0x10000000
#define DEBUG_SIZE 0x00100000
#define DEBUG_END_ADDRESS (DEBUG_START_ADDRESS + DEBUG_SIZE)

//always-on peripherals
#define AO_PERIPHERAL_START_ADDRESS 0x20000000
#define AO_PERIPHERAL_SIZE 0x00100000
#define AO_PERIPHERAL_END_ADDRESS (AO_PERIPHERAL_START_ADDRESS + AO_PERIPHERAL_SIZE)

#define SOC_CTRL_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x00000000)
#define SOC_CTRL_SIZE 0x00010000
#define SOC_CTRL_END_ADDRESS (SOC_CTRL_START_ADDRESS + SOC_CTRL_SIZE)

#define BOOTROM_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x00010000)
#define BOOTROM_SIZE 0x00010000
#define BOOTROM_END_ADDRESS (BOOTROM_START_ADDRESS + BOOTROM_SIZE)

#define SPI_FLASH_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x00020000)
#define SPI_FLASH_SIZE 0x00008000
#define SPI_FLASH_END_ADDRESS (SPI_FLASH_START_ADDRESS + SPI_FLASH_SIZE)

#define SPI_MEMIO_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x00028000)
#define SPI_MEMIO_SIZE 0x00008000
#define SPI_MEMIO_END_ADDRESS (SPI_MEMIO_START_ADDRESS + SPI_MEMIO_SIZE)

#define SPI_HOST_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x00030000)
#define SPI_HOST_SIZE 0x00010000
#define SPI_HOST_END_ADDRESS (SPI_HOST_START_ADDRESS + SPI_HOST_SIZE)

#define POWER_MANAGER_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x00040000)
#define POWER_MANAGER_SIZE 0x00010000
#define POWER_MANAGER_END_ADDRESS (POWER_MANAGER_START_ADDRESS + POWER_MANAGER_SIZE)

#define RV_TIMER_AO_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x00050000)
#define RV_TIMER_AO_SIZE 0x00010000
#define RV_TIMER_AO_END_ADDRESS (RV_TIMER_AO_START_ADDRESS + RV_TIMER_AO_SIZE)

#define DMA_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x00060000)
#define DMA_SIZE 0x00010000
#define DMA_END_ADDRESS (DMA_START_ADDRESS + DMA_SIZE)

#define FAST_INTR_CTRL_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x00070000)
#define FAST_INTR_CTRL_SIZE 0x00010000
#define FAST_INTR_CTRL_END_ADDRESS (FAST_INTR_CTRL_START_ADDRESS + FAST_INTR_CTRL_SIZE)

#define EXT_PERIPHERAL_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x00080000)
#define EXT_PERIPHERAL_SIZE 0x00010000
#define EXT_PERIPHERAL_END_ADDRESS (EXT_PERIPHERAL_START_ADDRESS + EXT_PERIPHERAL_SIZE)

#define PAD_CONTROL_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x00090000)
#define PAD_CONTROL_SIZE 0x00010000
#define PAD_CONTROL_END_ADDRESS (PAD_CONTROL_START_ADDRESS + PAD_CONTROL_SIZE)

#define GPIO_AO_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x000A0000)
#define GPIO_AO_SIZE 0x00010000
#define GPIO_AO_END_ADDRESS (GPIO_AO_START_ADDRESS + GPIO_AO_SIZE)

#define UART_START_ADDRESS (AO_PERIPHERAL_START_ADDRESS + 0x000B0000)
#define UART_SIZE 0x00010000
#define UART_END_ADDRESS (UART_START_ADDRESS + UART_SIZE)


//switch-on/off peripherals
#define PERIPHERAL_START_ADDRESS 0x30000000
#define PERIPHERAL_SIZE 0x00100000
#define PERIPHERAL_END_ADDRESS (PERIPHERAL_START_ADDRESS + PERIPHERAL_SIZE)

#define RV_PLIC_START_ADDRESS (PERIPHERAL_START_ADDRESS + 0x00000000)
#define RV_PLIC_SIZE 0x00010000
#define RV_PLIC_END_ADDRESS (RV_PLIC_START_ADDRESS + RV_PLIC_SIZE)

#define GPIO_START_ADDRESS (PERIPHERAL_START_ADDRESS + 0x00020000)
#define GPIO_SIZE 0x00010000
#define GPIO_END_ADDRESS (GPIO_START_ADDRESS + GPIO_SIZE)

#define I2C_START_ADDRESS (PERIPHERAL_START_ADDRESS + 0x00030000)
#define I2C_SIZE 0x00010000
#define I2C_END_ADDRESS (I2C_START_ADDRESS + I2C_SIZE)

#define RV_TIMER_START_ADDRESS (PERIPHERAL_START_ADDRESS + 0x00040000)
#define RV_TIMER_SIZE 0x00010000
#define RV_TIMER_END_ADDRESS (RV_TIMER_START_ADDRESS + RV_TIMER_SIZE)

#define SPI2_START_ADDRESS (PERIPHERAL_START_ADDRESS + 0x00050000)
#define SPI2_SIZE 0x00010000
#define SPI2_END_ADDRESS (SPI2_START_ADDRESS + SPI2_SIZE)


#define EXT_SLAVE_START_ADDRESS 0xF0000000
#define EXT_SLAVE_SIZE 0x01000000
#define EXT_SLAVE_END_ADDRESS (EXT_SLAVE_START_ADDRESS + EXT_SLAVE_SIZE)

#define FLASH_MEM_START_ADDRESS 0x40000000
#define FLASH_MEM_SIZE 0x01000000
#define FLASH_MEM_END_ADDRESS (FLASH_MEM_START_ADDRESS + FLASH_MEM_SIZE)

#define NULL_INTR 0
#define UART_INTR_TX_WATERMARK 1
#define UART_INTR_RX_WATERMARK 2
#define UART_INTR_TX_EMPT 3
#define UART_INTR_RX_OVERFLOW 4
#define UART_INTR_RX_FRAME_ERR 5
#define UART_INTR_RX_BREAK_ERR 6
#define UART_INTR_RX_TIMEOUT 7
#define UART_INTR_RX_PARITY_ERR 8
#define GPIO_INTR_8 9
#define GPIO_INTR_9 10
#define GPIO_INTR_10 11
#define GPIO_INTR_11 12
#define GPIO_INTR_12 13
#define GPIO_INTR_13 14
#define GPIO_INTR_14 15
#define GPIO_INTR_15 16
#define GPIO_INTR_16 17
#define GPIO_INTR_17 18
#define GPIO_INTR_18 19
#define GPIO_INTR_19 20
#define GPIO_INTR_20 21
#define GPIO_INTR_21 22
#define GPIO_INTR_22 23
#define GPIO_INTR_23 24
#define GPIO_INTR_24 25
#define GPIO_INTR_25 26
#define GPIO_INTR_26 27
#define GPIO_INTR_27 28
#define GPIO_INTR_28 29
#define GPIO_INTR_29 30
#define GPIO_INTR_30 31
#define GPIO_INTR_31 32
#define INTR_FMT_WATERMARK 33
#define INTR_RX_WATERMARK 34
#define INTR_FMT_OVERFLOW 35
#define INTR_RX_OVERFLOW 36
#define INTR_NAK 37
#define INTR_SCL_INTERFERENCE 38
#define INTR_SDA_INTERFERENCE 39
#define INTR_STRETCH_TIMEOUT 40
#define INTR_SDA_UNSTABLE 41
#define INTR_TRANS_COMPLETE 42
#define INTR_TX_EMPTY 43
#define INTR_TX_NONEMPTY 44
#define INTR_TX_OVERFLOW 45
#define INTR_ACQ_OVERFLOW 46
#define INTR_ACK_STOP 47
#define INTR_HOST_TIMEOUT 48
#define SPI2_INTR_EVENT 49
#define EXT_INTR_0 50
#define EXT_INTR_1 51
#define EXT_INTR_2 52
#define EXT_INTR_3 53
#define EXT_INTR_4 54
#define EXT_INTR_5 55
#define EXT_INTR_6 56
#define EXT_INTR_7 57
#define EXT_INTR_8 58
#define EXT_INTR_9 59
#define EXT_INTR_10 60
#define EXT_INTR_11 61
#define EXT_INTR_12 62
#define EXT_INTR_13 63

#define PAD_CLK_ATTRIBUTE 0
#define PAD_RST_ATTRIBUTE 1
#define PAD_BOOT_SELECT_ATTRIBUTE 2
#define PAD_EXECUTE_FROM_FLASH_ATTRIBUTE 3
#define PAD_JTAG_TCK_ATTRIBUTE 4
#define PAD_JTAG_TMS_ATTRIBUTE 5
#define PAD_JTAG_TRST_ATTRIBUTE 6
#define PAD_JTAG_TDI_ATTRIBUTE 7
#define PAD_JTAG_TDO_ATTRIBUTE 8
#define PAD_UART_RX_ATTRIBUTE 9
#define PAD_UART_TX_ATTRIBUTE 10
#define PAD_EXIT_VALID_ATTRIBUTE 11
#define PAD_GPIO_0_ATTRIBUTE 12
#define PAD_GPIO_1_ATTRIBUTE 13
#define PAD_GPIO_2_ATTRIBUTE 14
#define PAD_GPIO_3_ATTRIBUTE 15
#define PAD_GPIO_4_ATTRIBUTE 16
#define PAD_GPIO_5_ATTRIBUTE 17
#define PAD_GPIO_6_ATTRIBUTE 18
#define PAD_GPIO_7_ATTRIBUTE 19
#define PAD_GPIO_8_ATTRIBUTE 20
#define PAD_GPIO_9_ATTRIBUTE 21
#define PAD_GPIO_10_ATTRIBUTE 22
#define PAD_GPIO_11_ATTRIBUTE 23
#define PAD_GPIO_12_ATTRIBUTE 24
#define PAD_GPIO_13_ATTRIBUTE 25
#define PAD_GPIO_14_ATTRIBUTE 26
#define PAD_GPIO_15_ATTRIBUTE 27
#define PAD_GPIO_16_ATTRIBUTE 28
#define PAD_GPIO_17_ATTRIBUTE 29
#define PAD_GPIO_18_ATTRIBUTE 30
#define PAD_GPIO_19_ATTRIBUTE 31
#define PAD_GPIO_20_ATTRIBUTE 32
#define PAD_GPIO_21_ATTRIBUTE 33
#define PAD_GPIO_22_ATTRIBUTE 34
#define PAD_SPI_FLASH_SCK_ATTRIBUTE 35
#define PAD_SPI_FLASH_CS_0_ATTRIBUTE 36
#define PAD_SPI_FLASH_CS_1_ATTRIBUTE 37
#define PAD_SPI_FLASH_SD_0_ATTRIBUTE 38
#define PAD_SPI_FLASH_SD_1_ATTRIBUTE 39
#define PAD_SPI_FLASH_SD_2_ATTRIBUTE 40
#define PAD_SPI_FLASH_SD_3_ATTRIBUTE 41
#define PAD_SPI_SCK_ATTRIBUTE 42
#define PAD_SPI_CS_0_ATTRIBUTE 43
#define PAD_SPI_CS_1_ATTRIBUTE 44
#define PAD_SPI_SD_0_ATTRIBUTE 45
#define PAD_SPI_SD_1_ATTRIBUTE 46
#define PAD_SPI_SD_2_ATTRIBUTE 47
#define PAD_SPI_SD_3_ATTRIBUTE 48
#define PAD_SPI2_CS_0_ATTRIBUTE 49
#define PAD_SPI2_CS_1_ATTRIBUTE 50
#define PAD_SPI2_SCK_ATTRIBUTE 51
#define PAD_SPI2_SD_0_ATTRIBUTE 52
#define PAD_SPI2_SD_1_ATTRIBUTE 53
#define PAD_SPI2_SD_2_ATTRIBUTE 54
#define PAD_SPI2_SD_3_ATTRIBUTE 55
#define PAD_I2C_SCL_ATTRIBUTE 56
#define PAD_I2C_SDA_ATTRIBUTE 57

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  // COREV_MINI_MCU_H_
